Minisearch:
	g++ -g -o Minisearch   List.h Interface.cpp  Minisearch.cpp  Statistics.cpp Data_Structures/*.cpp Data_Structures/Trie/*.cpp Data_Structures/Posting_List/*.cpp Data_Structures/Document/*.cpp 

clean:
	rm -f Minisearch 
